WIP: simplify core
encryption4all/irmaseal pull request #7
Opened 2021-04-23 18:59 UTC by rowanG077

- [x] Removed streaming from core
- [x] Rewritten core to handle only metadata and key generation
- [ ] Rewrite core tests
- [ ] Create new irmaseal-stream package that handles symmetric crypto in rust.

2021-05-04 13:42 UTC, leonbotros requested changes
Looks good! Some minor changes requested.

2021-05-04 13:42 UTC, leonbotros commented on irmaseal-core/src/metadata_reader.rs
> +    fn parse_meta_data(&self) -> Result<Metadata, Error> {
style: `parse_meta_data` -> `parse_metadata`

2021-05-04 13:43 UTC, rowanG077 commented on irmaseal-core/Cargo.toml
> +stream = ["aes", "ctr", "cfb-mode" ]
Yes I think. I will check this

2021-05-04 13:44 UTC, rowanG077 commented on irmaseal-cli/src/decrypt.rs
> +            &mut std::fs::File::create("./unsealed").unwrap(),
Trye

2021-05-04 13:44 UTC, rowanG077 commented on irmaseal-core/src/lib.rs
> +pub(crate) const SYMMETRIC_CRYPTO_IDENTIFIER: &str = "AES256-CTR";
`AES256-CTR64BE`?

2021-05-04 13:46 UTC, leonbotros commented on irmaseal-core/src/lib.rs
> +pub(crate) const SYMMETRIC_CRYPTO_IDENTIFIER: &str = "AES256-CTR";
I agree, that would be most compact and it includes everything necessary

2021-05-04 14:28 UTC, rowanG077 commented on irmaseal-core/src/lib.rs
> +pub(crate) const SYMMETRIC_CRYPTO_IDENTIFIER: &str = "AES256-CTR";
It does not include how to initialize the counter but maybe that is too specific?

2021-05-04 14:36 UTC, leonbotros commented on irmaseal-core/src/lib.rs
> +pub(crate) const SYMMETRIC_CRYPTO_IDENTIFIER: &str = "AES256-CTR";
If you include `CTR64-BE`, any consumer library/application can initialize the counter if they want to. If some application wants to start at 0 and perform additions that are checked for overflow, one could pass an IV with the last 8 bytes set to the representation of `0u64.to_be_bytes()` for example.

2021-05-04 14:38 UTC, leonbotros commented on irmaseal-core/src/lib.rs
> +pub(crate) const SYMMETRIC_CRYPTO_IDENTIFIER: &str = "AES256-CTR";
I.e., by ignoring some of the IV from a `metadata`.

2021-05-06 10:33 UTC, leonbotros approved these changes

2021-05-06 10:55 UTC, merged